---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: prepare.yml

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: configure.yml
