---
# code: language=ansible
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  register: _pre_update_apt_cache
  until: _pre_update_apt_cache is succeeded
  when:
    - ansible_pkg_mgr == "apt"

- name: Install dependencies
  become: true
  ansible.builtin.package:
    name: "{{ resilio_dependencies }}"
    state: present
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
