---
# code: language=ansible
- name: Converge
  hosts: all
  become: true
  roles:
    - ansible-role-resilio
  pre_tasks:
    - name: Install netstat on Fedora
      ansible.builtin.package:
        name: net-tools
        state: present
      when:
        - ansible_pkg_mgr == "dnf"
